function(library_from_folder NAME)
    if (EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/src")
        string(TOUPPER ${NAME} UPPERNAME)
        file(GLOB ${UPPERNAME}_SOURCE "src/*.cpp")
        file(GLOB ${UPPERNAME}_HEADERS "include/*.h")
        add_library(${NAME} ${${UPPERNAME}_SOURCE} ${${UPPERNAME}_HEADERS})
        target_include_directories(${NAME} PUBLIC include)
    else ()
        add_library(${NAME} INTERFACE IMPORTED GLOBAL)
        target_include_directories(${NAME} INTERFACE include/)
    endif ()
endfunction()